console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
console.log('hola Mundo');
let a = 23;
alert(a);
